"use client";
import { useState, useEffect } from "react";
import { FaBell, FaDownload, FaFileExcel, FaFilePdf, FaSearch, FaShare, FaHistory, FaSave } from "react-icons/fa";
import { FiDownloadCloud } from "react-icons/fi";
import { db } from "@/firebaseConfig";
import { onValue, ref, push } from "firebase/database";
import { useAuth } from "../../hooks/useAuth";
import { generateReportSummary, generateFallbackReport } from "@/lib/gemini";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";

interface OperatorReportsProps {
  onNavigate?: (page: string) => void;
}

interface Generator {
  id: string;
  serialNo: string;
  brand: string;
  size: string;
  status: string;
  shopId: string;
  location?: string;
  installedDate?: number;
}

interface Issue {
  id: string;
  equipmentId: string;
  description: string;
  severity: string;
  status: string;
  createdAt: number;
}

interface ServiceLog {
  id: string;
  generatorId: string;
  serviceType: string;
  serviceDate: string;
  notes: string;
  cost?: number;
  nextDueDate?: string;
}

interface SavedReport {
  id: string;
  title: string;
  createdAt: number;
  createdBy: string;
  shopId: string;
  data: {
    generators: Generator[];
    issues: Issue[];
    serviceLogs: ServiceLog[];
    summary: string;
  };
}

export default function OperatorReports({ onNavigate }: OperatorReportsProps) {
  const { userProfile } = useAuth();
  const [searchText, setSearchText] = useState("");
  const [generators, setGenerators] = useState<Generator[]>([]);
  const [issues, setIssues] = useState<Issue[]>([]);
  const [serviceLogs, setServiceLogs] = useState<ServiceLog[]>([]);
  const [selectedGenerator, setSelectedGenerator] = useState<Generator | null>(null);
  const [showGeneratorDetails, setShowGeneratorDetails] = useState(false);
  const [reportSummary, setReportSummary] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [showErrorModal, setShowErrorModal] = useState(false);
  const [autoGeneratedReport, setAutoGeneratedReport] = useState(false);
  const [showReportHistory, setShowReportHistory] = useState(false);
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);
  const [savingReport, setSavingReport] = useState(false);

  useEffect(() => {
    if (!userProfile?.shopId) return;

    const unsubscribers: Array<() => void> = [];

    const loadData = async () => {
      const generatorsRef = ref(db, "generators");
      const offGenerators = onValue(generatorsRef, (snapshot) => {
        const data = snapshot.val();
        if (data) {
          const shopGenerators = Object.keys(data)
            .map((key) => ({
              id: key,
              serialNo: data[key].serialNo || data[key].serial_no || "N/A",
              brand: data[key].brand || "N/A",
              size: data[key].size || "N/A",
              status: data[key].status || "unknown",
              shopId: data[key].shopId || data[key].shop_id,
              location: data[key].location,
              installedDate: data[key].installedDate || data[key].installed_date,
            }))
            .filter((gen) => gen.shopId === userProfile.shopId);
          setGenerators(shopGenerators);
        } else {
          setGenerators([]);
        }
      });
      unsubscribers.push(() => offGenerators());

      const issuesRef = ref(db, "issues");
      const offIssues = onValue(issuesRef, (snapshot) => {
        const data = snapshot.val();
        if (data) {
          const issuesList = Object.keys(data).map((key) => ({
            id: key,
            equipmentId: data[key].equipmentId || data[key].equipment_id,
            description: data[key].description || "No description",
            severity: data[key].severity || "medium",
            status: data[key].status || "open",
            createdAt: data[key].createdAt || Date.now(),
          }));
          setIssues(issuesList);
        } else {
          setIssues([]);
        }
      });
      unsubscribers.push(() => offIssues());

      const serviceLogsRef = ref(db, "serviceLogs");
      const offServiceLogs = onValue(serviceLogsRef, (snapshot) => {
        const data = snapshot.val();
        if (data) {
          const logs = Object.keys(data).map((key) => ({
            id: key,
            generatorId: data[key].generatorId,
            serviceType: data[key].serviceType || "Maintenance",
            serviceDate: data[key].serviceDate,
            notes: data[key].notes || "No notes available",
            cost: data[key].cost,
            nextDueDate: data[key].nextDueDate,
          }));
          setServiceLogs(logs);
        } else {
          setServiceLogs([]);
        }
        setLoading(false);
      });
      unsubscribers.push(() => offServiceLogs());

      const reportsRef = ref(db, `savedReports/${userProfile.shopId}`);
      const offSavedReports = onValue(reportsRef, (snapshot) => {
        const data = snapshot.val();
        if (data) {
          const reportsList = Object.keys(data)
            .map((key) => ({ id: key, ...data[key] }))
            .sort((a: any, b: any) => b.createdAt - a.createdAt);
          setSavedReports(reportsList as unknown as SavedReport[]);
        } else {
          setSavedReports([]);
        }
      });
      unsubscribers.push(() => offSavedReports());
    };

    loadData();

    return () => {
      unsubscribers.forEach((off) => {
        try {
          off();
        } catch {}
      });
    };
  }, [userProfile?.shopId]);

  useEffect(() => {
    if (!loading && generators.length > 0 && !reportSummary && !autoGeneratedReport) {
      const fallbackReport = generateFallbackReport(generators, issues, serviceLogs);
      setReportSummary(fallbackReport);
      setAutoGeneratedReport(true);
    }
  }, [loading, generators, issues, serviceLogs, reportSummary, autoGeneratedReport]);

  const generateAIReport = async () => {
    setGeneratingReport(true);
    setAutoGeneratedReport(false);
    try {
      const summary = await generateReportSummary(generators, issues, serviceLogs);
      setReportSummary(summary);
    } catch (error: unknown) {
      console.error("Error generating report:", error);
      const err = error as Error;
      if (err?.message === "AI_SERVICE_UNAVAILABLE") {
        setShowErrorModal(true);
      }
      const fallbackReport = generateFallbackReport(generators, issues, serviceLogs);
      setReportSummary(fallbackReport);
      setAutoGeneratedReport(true);
    } finally {
      setGeneratingReport(false);
    }
  };

  function removeUndefined(obj: any): any {
    if (Array.isArray(obj)) {
      return obj.map(removeUndefined);
    } else if (typeof obj === "object" && obj !== null) {
      const cleaned: any = {};
      for (const [key, value] of Object.entries(obj)) {
        if (value !== undefined) {
          cleaned[key] = removeUndefined(value);
        }
      }
      return cleaned;
    }
    return obj;
  }

  const saveReportToFirebase = async () => {
    if (!userProfile?.shopId || !reportSummary) return;

    setSavingReport(true);
    try {
      const cleanedGenerators = generators?.map((g) => removeUndefined(g)) ?? [];
      const cleanedIssues = issues?.map((i) => removeUndefined(i)) ?? [];
      const cleanedServiceLogs = serviceLogs?.map((s) => ({
        ...s,
        cost: s.cost ?? 0,
      })) ?? [];

      const reportData: Omit<SavedReport, "id"> = {
        title: `Report - ${new Date().toLocaleDateString()}`,
        createdAt: Date.now(),
        createdBy: userProfile.id,
        shopId: userProfile.shopId,
        data: {
          generators: cleanedGenerators,
          issues: cleanedIssues,
          serviceLogs: cleanedServiceLogs,
          summary: removeUndefined(reportSummary),
        },
      };

      const cleanReport = removeUndefined(reportData);

      const reportsRef = ref(db, `savedReports/${userProfile.shopId}`);
      await push(reportsRef, cleanReport);

      alert("Report saved successfully!");
    } catch (error) {
      console.error("Error saving report:", error);
      alert("Failed to save report. Please try again.");
    } finally {
      setSavingReport(false);
    }
  };

  const loadSavedReport = (report: SavedReport) => {
    setGenerators(report.data.generators);
    setIssues(report.data.issues);
    setServiceLogs(report.data.serviceLogs);
    setReportSummary(report.data.summary);
    setShowReportHistory(false);
  };

  const downloadExcelReport = () => {
    const workbook = XLSX.utils.book_new();

    const generatorsData = generators.map((g) => ({
      "Generator ID": g.id,
      "Serial Number": g.serialNo,
      Brand: g.brand,
      Size: g.size,
      Status: g.status,
      Location: g.location || "N/A",
    }));
    const generatorsSheet = XLSX.utils.json_to_sheet(generatorsData);
    XLSX.utils.book_append_sheet(workbook, generatorsSheet, "Generators");

    const issuesData = issues.map((i) => ({
      "Issue ID": i.id,
      Equipment: i.equipmentId,
      Description: i.description,
      Severity: i.severity,
      Status: i.status,
      Date: new Date(i.createdAt).toLocaleDateString(),
    }));
    const issuesSheet = XLSX.utils.json_to_sheet(issuesData);
    XLSX.utils.book_append_sheet(workbook, issuesSheet, "Issues");

    const serviceData = serviceLogs.map((s) => ({
      "Service ID": s.id,
      Generator: s.generatorId,
      "Service Type": s.serviceType,
      Date: s.serviceDate,
      Notes: s.notes,
      Cost: s.cost || 0,
    }));
    const serviceSheet = XLSX.utils.json_to_sheet(serviceData);
    XLSX.utils.book_append_sheet(workbook, serviceSheet, "Service Logs");

    XLSX.writeFile(workbook, `Generator_Report_${new Date().toISOString().split("T")[0]}.xlsx`);
  };

  const downloadPDFReport = () => {
    try {
      const doc = new jsPDF();

      doc.setFontSize(20);
      doc.text("Generator Management Report", 20, 20);

      doc.setFontSize(12);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 35);
      doc.text(`Center: ${userProfile?.name || "Unknown"}`, 20, 45);

      doc.setFontSize(14);
      doc.text("Summary Statistics", 20, 65);
      doc.setFontSize(10);
      doc.text(`Total Generators: ${generators.length}`, 20, 80);
      doc.text(`Active Issues: ${issues.filter((i) => i.status !== "closed").length}`, 20, 90);
      doc.text(`Service Records: ${serviceLogs.length}`, 20, 100);

      let yPosition = 120;
      doc.setFontSize(12);
      doc.text("Generator Details", 20, yPosition);
      yPosition += 15;

      doc.setFontSize(10);
      generators.forEach((g, index) => {
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(`${index + 1}. ${g.id} - ${g.serialNo} (${g.brand} ${g.size}) - Status: ${g.status}`, 20, yPosition);
        yPosition += 10;
      });

      if (reportSummary) {
        yPosition += 20;
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }

        doc.setFontSize(14);
        doc.text(autoGeneratedReport ? "System Analysis Summary" : "AI Analysis Summary", 20, yPosition);
        yPosition += 15;
        doc.setFontSize(10);

        const cleanText = reportSummary
          .replace(/#{1,6}\s*/g, "")
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/\*(.*?)\*/g, "$1")
          .replace(/•/g, "-")
          .replace(/\n\s*\n/g, "\n")
          .trim();

        const splitText = doc.splitTextToSize(cleanText, 170);

        splitText.forEach((line: string) => {
          if (yPosition > 280) {
            doc.addPage();
            yPosition = 20;
          }
          doc.text(line, 20, yPosition);
          yPosition += 5;
        });
      }

      doc.save(`Generator_Report_${new Date().toISOString().split("T")[0]}.pdf`);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Error generating PDF report. Please try again.");
    }
  };

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case "active":
      case "online":
        return "bg-green-100 text-green-800";
      case "inactive":
      case "offline":
        return "bg-red-100 text-red-800";
      case "under repair":
        return "bg-yellow-100 text-yellow-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const filteredGenerators = generators.filter(
    (g) =>
      g.id.toLowerCase().includes(searchText.toLowerCase()) ||
      g.serialNo.toLowerCase().includes(searchText.toLowerCase()) ||
      g.brand.toLowerCase().includes(searchText.toLowerCase())
  );

  const handleGeneratorClick = (generator: Generator) => {
    setSelectedGenerator(generator);
    setShowGeneratorDetails(true);
  };

  const getGeneratorServiceLogs = (generatorId: string) => {
    return serviceLogs.filter((log) => log.generatorId === generatorId);
  };

  const formatSummaryText = (text: string) => {
    return text
      .replace(/#{1,6}\s*/g, "")
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/•\s*/g, "")
      .split("\n")
      .filter((line) => line.trim())
      .map((line, index) => {
        const trimmedLine = line.trim();
        if (trimmedLine.includes(":") && !trimmedLine.startsWith("*") && !trimmedLine.startsWith("-")) {
          return `<div key=${index} class="mb-3"><h4 class="font-semibold text-gray-800 mb-2">${trimmedLine}</h4></div>`;
        } else if (trimmedLine.startsWith("-") || trimmedLine.startsWith("*")) {
          return `<div key=${index} class="ml-4 mb-1 flex items-start"><span class="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span><span class="text-gray-700">${trimmedLine
            .substring(1)
            .trim()}</span></div>`;
        } else {
          return `<div key=${index} class="mb-2 text-gray-700">${trimmedLine}</div>`;
        }
      })
      .join("");
  };

  if (loading) {
    return (
      <div className="flex-1 p-8 bg-gray-50 min-h-screen flex items-center justify-center text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
        <p className="text-gray-600">Loading report data...</p>
      </div>
    );
  }

  return (
    <div className="flex-1 bg-gray-50 min-h-screen">
      <div className="bg-white border-b border-gray-200 px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 data-cy="page-header" className="text-2xl font-bold text-blue-600">
              Reports
            </h1>
            <p data-cy="reports-center" className="text-sm text-gray-500">
              Own by This Center
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowReportHistory(true)}
              className="w-10 h-10 bg-green-500 text-white rounded-lg flex items-center justify-center hover:bg-green-600 transition-colors"
              title="Report History"
            >
              <FaHistory className="text-lg" />
            </button>
            <button className="w-10 h-10 bg-blue-500 text-white rounded-lg flex items-center justify-center hover:bg-blue-600 transition-colors">
              <FaBell className="text-lg" />
            </button>
          </div>
        </div>
      </div>

      <div className="p-6">
        <div className="mb-6">
          <div className="flex items-center gap-4">
            <div className="flex-1 max-w-md">
              <label className="block text-sm font-medium text-gray-700 mb-2">Gen ID</label>
              <div className="relative">
                <input
                  data-cy="serial-search"
                  type="text"
                  placeholder="Serial Number"
                  value={searchText}
                  onChange={(e) => setSearchText(e.target.value)}
                  className="w-full pl-4 pr-10 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
                <button className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  <FaSearch />
                </button>
              </div>
            </div>
            <div className="flex items-center gap-2 mt-6">
              <span className="text-sm text-gray-600">Hinted search text</span>
              <button className="p-2 text-gray-400 hover:text-gray-600">
                <FaSearch />
              </button>
            </div>
          </div>
        </div>

        <div data-cy="generator-list" className="space-y-4 mb-8">
          {filteredGenerators.length > 0 ? (
            filteredGenerators.map((generator) => (
              <div
                key={generator.id}
                className="bg-white rounded-lg border border-gray-200 p-4 hover:shadow-md transition-shadow cursor-pointer"
                onClick={() => handleGeneratorClick(generator)}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-3 h-3 bg-green-400 rounded-full"></div>
                    <div>
                      <h3 className="font-semibold text-gray-900">Generator {generator.id}</h3>
                      <p className="text-sm text-gray-500">
                        <span className={`inline-block px-2 py-1 rounded-full text-xs ${getStatusColor(generator.status)}`}>
                          {generator.status}
                        </span>
                      </p>
                    </div>
                  </div>
                  <div className="w-16 h-12 bg-green-400 rounded-r-lg"></div>
                </div>
              </div>
            ))
          ) : (
            <div className="bg-white rounded-lg border border-gray-200 p-8 text-center">
              <p className="text-gray-500">No generators found matching your search criteria</p>
              <p className="text-sm text-gray-400 mt-2">Data not available</p>
            </div>
          )}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl border border-blue-200 p-6 min-h-[400px]">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-blue-900">Generator Replace</h3>
              <div className="w-8 h-8 bg-blue-500 rounded-lg flex items-center justify-center">
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
                </svg>
              </div>
            </div>

            {generators.length > 0 ? (
              <div className="space-y-4">
                <p className="text-blue-800 text-sm mb-4">Generator deployment status for this center</p>
                <div className="max-h-72 overflow-y-auto space-y-3 pr-2">
                  {generators.map((generator) => (
                    <div key={generator.id} className="bg-white/70 rounded-lg p-3 border border-blue-200">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div
                            className={`w-3 h-3 rounded-full ${
                              generator.status?.toLowerCase() === "active"
                                ? "bg-green-400"
                                : generator.status?.toLowerCase() === "under repair"
                                ? "bg-red-400"
                                : "bg-yellow-400"
                            }`}
                          ></div>
                          <div>
                            <p className="font-medium text-gray-900 text-sm">
                              {generator.id} - {generator.serialNo}
                            </p>
                            <p className="text-xs text-gray-600">
                              {generator.brand} {generator.size} • {generator.status}
                            </p>
                          </div>
                        </div>
                        <span className="text-xs text-blue-600 font-medium">
                          {generator.status?.toLowerCase() === "active" ? "Deployed" : "Pending"}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-4 pt-4 border-t border-blue-200">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-blue-800">Total Generators:</span>
                    <span className="font-semibold text-blue-900">{generators.length}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm mt-1">
                    <span className="text-blue-800">Active:</span>
                    <span className="font-semibold text-green-700">
                      {generators.filter((g) => g.status?.toLowerCase() === "active").length}
                    </span>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center h-48">
                <div className="text-center">
                  <div className="w-16 h-16 bg-blue-200 rounded-full flex items-center justify-center mx-auto mb-3">
                    <svg className="w-8 h-8 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <p className="text-blue-800 font-medium">No Generators Available</p>
                  <p className="text-blue-600 text-sm mt-1">Data not available</p>
                </div>
              </div>
            )}
          </div>

          <div data-cy="service-report-section" className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl border border-green-200 p-6 min-h-[400px]">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-green-900">Service Report</h3>
              <div className="w-8 h-8 bg-green-500 rounded-lg flex items-center justify-center">
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                  <path fillRule="evenodd" d="M4 5a2 2 0 012-2v1a2 2 0 002 2v1a2 2 0 002 2v1a2 2 0 002 2v1a2 2 0 01-2 2H6a2 2 0 01-2-2V5z" clipRule="evenodd" />
                </svg>
              </div>
            </div>

            {serviceLogs.length > 0 ? (
              <div className="space-y-4">
                <p className="text-green-800 text-sm mb-4">Service Report for Generator G0098 will be available on other next Service</p>

                <div className="space-y-3">
                  {serviceLogs.slice(0, 5).map((log) => (
                    <div key={log.id} className="bg-white/70 rounded-lg p-3 border border-green-200">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center">
                            <span className="text-xs font-medium text-green-600">A</span>
                          </div>
                          <div>
                            <p className="font-medium text-gray-900 text-sm">{log.serviceType}</p>
                            <p className="text-xs text-gray-600">Generator: {log.generatorId} • {log.serviceDate}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-green-600">Checked</span>
                          <div className="w-4 h-4 bg-green-500 rounded-sm flex items-center justify-center">
                            <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                              <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                            </svg>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-4 pt-4 border-t border-green-200">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-green-800">Total Services:</span>
                    <span className="font-semibold text-green-900">{serviceLogs.length}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm mt-1">
                    <span className="text-green-800">This Month:</span>
                    <span className="font-semibold text-green-700">
                      {serviceLogs.filter((log) => {
                        const serviceDate = new Date(log.serviceDate);
                        const currentMonth = new Date().getMonth();
                        const currentYear = new Date().getFullYear();
                        return serviceDate.getMonth() === currentMonth && serviceDate.getFullYear() === currentYear;
                      }).length}
                    </span>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center h-48">
                <div className="text-center">
                  <div className="w-16 h-16 bg-green-200 rounded-full flex items-center justify-center mx-auto mb-3">
                    <svg className="w-8 h-8 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                      <path fillRule="evenodd" d="M4 5a2 2 0 012-2v1a2 2 0 002 2v1a2 2 0 002 2v1a2 2 0 002 2v1a2 2 0 01-2 2H6a2 2 0 01-2-2V5z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <p className="text-green-800 font-medium">No Service Reports Available</p>
                  <p className="text-green-600 text-sm mt-1">Data not available</p>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Service Reports</h2>
            <div className="flex gap-2">
              <button
                data-cy="generate-report"
                onClick={generateAIReport}
                disabled={generatingReport}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-blue-400 transition-colors flex items-center gap-2"
              >
                {generatingReport ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                    Generating...
                  </>
                ) : (
                  <>
                    <FaBell />
                    Generate Report
                  </>
                )}
              </button>
              {reportSummary && (
                <button
                  data-cy="save-report"
                  onClick={saveReportToFirebase}
                  disabled={savingReport}
                  className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:bg-purple-400 transition-colors flex items-center gap-2"
                >
                  {savingReport ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                      Saving...
                    </>
                  ) : (
                    <>
                      <FaSave />
                      Save Report
                    </>
                  )}
                </button>
              )}
              <button
                data-cy="download-excel"
                onClick={downloadExcelReport}
                className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2"
              >
                <FaFileExcel />
                Excel
              </button>
              <button
                data-cy="download-pdf"
                onClick={downloadPDFReport}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors flex items-center gap-2"
              >
                <FaFilePdf />
                PDF
              </button>
            </div>
          </div>

          {serviceLogs.length > 0 ? (
            <div className="space-y-3">
              {serviceLogs.slice(0, 5).map((log) => (
                <div key={log.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                    <div>
                      <p className="font-medium text-gray-900">{log.serviceType}</p>
                      <p className="text-sm text-gray-500">Generator: {log.generatorId}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-gray-600">{log.serviceDate}</p>
                    {log.cost && <p className="text-sm font-medium text-green-600">LKR {log.cost}</p>}
                  </div>
                </div>
              ))}
              {serviceLogs.length > 5 && (
                <p className="text-sm text-gray-500 text-center pt-2">And {serviceLogs.length - 5} more service records...</p>
              )}
            </div>
          ) : (
            <div className="text-center py-8">
              <p className="text-gray-500">No service reports available</p>
              <p className="text-sm text-gray-400 mt-2">Data not available</p>
            </div>
          )}
        </div>

        {reportSummary && (
          <div data-cy="summary-section" className="bg-white rounded-lg border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">{autoGeneratedReport ? "System Analysis Summary" : "AI Analysis Summary"}</h3>
              {autoGeneratedReport && <span className="text-xs bg-blue-100 text-blue-800 px-3 py-1 rounded-full font-medium">System Generated</span>}
            </div>
            <div className="bg-gradient-to-br from-gray-50 to-blue-50 rounded-xl p-6 border border-gray-200">
              <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed" dangerouslySetInnerHTML={{ __html: formatSummaryText(reportSummary) }} />
            </div>
          </div>
        )}
      </div>

      {showReportHistory && (
        <div data-cy="report-history-modal" className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6 border-b border-gray-200">
              <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-gray-900">Report History</h2>
                <button onClick={() => setShowReportHistory(false)} className="text-gray-400 hover:text-gray-600 text-2xl">
                  ×
                </button>
              </div>
            </div>

            <div className="p-6">
              {savedReports.length > 0 ? (
                <div className="space-y-4">
                  {savedReports.map((report) => (
                    <div key={report.id} className="bg-gray-50 rounded-lg p-4 border border-gray-200 hover:shadow-md transition-shadow">
                      <div className="flex items-center justify-between">
                        <div>
                          <h4 className="font-semibold text-gray-900">{report.title}</h4>
                          <p className="text-sm text-gray-600">
                            Created: {new Date(report.createdAt).toLocaleDateString()} at {new Date(report.createdAt).toLocaleTimeString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            {report.data.generators.length} generators • {report.data.issues.length} issues • {report.data.serviceLogs.length} service logs
                          </p>
                        </div>
                        <button onClick={() => loadSavedReport(report)} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                          Load Report
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <FaHistory className="mx-auto h-12 w-12 text-gray-400 mb-4" />
                  <h3 className="text-lg font-medium text-gray-900 mb-2">No saved reports</h3>
                  <p className="text-gray-500">Generate and save reports to see them here.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Error modal placeholder
      <ErrorModal
        isOpen={showErrorModal}
        onClose={() => setShowErrorModal(false)}
        type="warning"
      /> */}
    </div>
  );
}

